/**
 * GET /api/quiz/review
 *
 * Returns a daily review session: 1–2 questions per overdue concept (up to 5
 * concepts → max ~10 questions) generated by AssessmentAgent Haiku.
 * Implements Phase 6 SRS spec §7.2.
 *
 * Response: { questions: QuizQuestion[], conceptCount: number }
 */

import { NextResponse }              from "next/server";
import { createClient }              from "@/lib/supabase/server";
import { requireApproved }           from "@/lib/auth/approval";
import { getDailyReviewQueue }       from "@/lib/srs/queue";
import { generateReviewQuestion }    from "@/lib/agents/assessment";
import type { ConceptMeta }          from "@/lib/agents/assessment";

export async function GET() {
  try {
    const guard = await requireApproved();
    if (guard.error) return guard.error;
    const { user } = guard;
    const supabase = await createClient();

    // ── 1. Fetch due concepts (cap at 5 for a reasonable session length) ──────
    const queue = await getDailyReviewQueue(user.id, supabase, 5);

    if (queue.length === 0) {
      return NextResponse.json({ questions: [], conceptCount: 0 });
    }

    // ── 2. Load concept metadata for all due concepts ─────────────────────────
    const conceptIds = queue.map((r) => r.concept_id);
    const { data: concepts } = await supabase
      .from("concepts")
      .select(
        "id, name, description, domain, bloom_level, learning_objectives, common_misconceptions"
      )
      .in("id", conceptIds);

    const conceptMap = Object.fromEntries(
      (concepts ?? []).map((c) => [c.id, c])
    );

    // ── 3. Generate questions in parallel (Haiku, 1–2 per concept) ───────────
    const questionSets = await Promise.all(
      queue.map(async (item) => {
        const dbConcept = conceptMap[item.concept_id];
        const meta: ConceptMeta = dbConcept
          ? {
              id:                    dbConcept.id,
              name:                  dbConcept.name,
              description:           dbConcept.description,
              domain:                dbConcept.domain,
              bloom_level:           dbConcept.bloom_level,
              learning_objectives:   dbConcept.learning_objectives   ?? [],
              common_misconceptions: dbConcept.common_misconceptions ?? [],
            }
          : {
              id:          item.concept_id,
              name:        item.concept_id,
              description: `Review: ${item.concept_id}`,
            };

        return generateReviewQuestion(meta, item.mastery_score);
      })
    );

    const questions = questionSets.flat();

    return NextResponse.json({ questions, conceptCount: queue.length });
  } catch (err) {
    console.error("GET /api/quiz/review error:", err);
    return NextResponse.json({ error: "Failed to generate review" }, { status: 500 });
  }
}
