import { cn } from "@/lib/utils";
import { COLUMN, COLUMN_16, WORDMARK } from "@/components/brand/markPaths";

/**
 * The Aristo mark (R1 "The Column", decisions.md V8.0), the one component
 * behind every place it renders: the landing nav, the classroom top bar in
 * /learn and /demo, the loading screen and the create-teacher header.
 *
 * `wordmark` is ARISTO in spaced capitals with the column as the I; `column`
 * is the column alone (icons, avatars); `column-small` is the same column
 * redrawn on a 16px grid, for use at 24px and below.
 *
 * Colour comes from the caller so the mark follows any theme: the ink takes
 * `currentColor` (set it with a `text-*` class) and the lit middle flute takes
 * its own colour from `litClassName` (also a `text-*` class). Size it with a
 * height class; the width follows the viewBox.
 *
 * The paths are generated by scripts/brand/build-mark.mjs. Server-safe: no
 * hooks, no client code.
 */

const SHAPES = {
  wordmark: WORDMARK,
  column: COLUMN,
  "column-small": COLUMN_16,
} as const;

export type AristoMarkVariant = keyof typeof SHAPES;

interface AristoMarkProps {
  variant?: AristoMarkVariant;
  className?: string;
  litClassName?: string;
  /**
   * The mark is usually next to a link label or an aria-label of its own, in
   * which case it is decorative. Pass `false` to expose it as an image named
   * "Aristo" when it stands alone.
   */
  decorative?: boolean;
}

export function AristoMark({
  variant = "wordmark",
  className,
  litClassName,
  decorative = true,
}: AristoMarkProps) {
  const shape = SHAPES[variant];
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={shape.viewBox}
      className={cn("block h-6 w-auto shrink-0 fill-current", className)}
      shapeRendering={variant === "column-small" ? "crispEdges" : undefined}
      role={decorative ? undefined : "img"}
      aria-label={decorative ? undefined : "Aristo"}
      aria-hidden={decorative ? true : undefined}
      focusable="false"
    >
      <path d={shape.ink} />
      <path d={shape.lit} className={cn("fill-current", litClassName)} />
    </svg>
  );
}
