import {
  ChartLine,
  EyeOff,
  GraduationCap,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";
import { Reveal } from "@/components/landing/Reveal";

interface Assurance {
  icon: LucideIcon;
  title: string;
  body: string;
}

const ASSURANCES: Assurance[] = [
  {
    icon: ShieldCheck,
    title: "Nobody signs themselves in",
    body: "Every new account waits for an administrator to approve it before a single lesson can start.",
  },
  {
    icon: ChartLine,
    title: "We track learning, not behaviour",
    body: "Which concepts are mastered, what was answered, how long a lesson ran. That is the list.",
  },
  {
    icon: EyeOff,
    title: "No camera, no location, no ads",
    body: "The microphone is only ever used for an answer your child chooses to speak. Nothing here is sold on.",
  },
];

export function ForParents() {
  return (
    <section
      id="for-parents"
      className="relative z-10 mx-auto w-full max-w-6xl scroll-mt-16 px-5 pt-20 sm:px-8 lg:pt-28"
    >
      <Reveal>
        <div className="grid gap-10 rounded-[32px] border border-aristo-beige-dark/80 bg-gradient-to-br from-[#FBF3E7] to-[#FFF7EE] p-7 sm:p-10 lg:grid-cols-2 lg:gap-14 lg:p-14">
          <div className="flex flex-col items-start gap-4">
            <span className="inline-flex items-center gap-2 rounded-full bg-white/75 px-3.5 py-1.5 text-[11px] font-bold uppercase tracking-[0.12em] text-aristo-orange-deep sm:text-xs">
              <GraduationCap className="size-3.5" />
              For parents
            </span>
            <h2 className="text-balance text-3xl font-extrabold leading-[1.12] tracking-[-0.03em] text-foreground sm:text-4xl lg:text-[36px]">
              For whoever is reading over their shoulder
            </h2>
            <p className="text-base leading-relaxed text-foreground/70 sm:text-[16.5px]">
              Aristo is an early prototype built for grades 6–8. Lessons are
              generated by AI, which means they can be wrong — it is something to
              learn alongside, not a source to cite.
            </p>
          </div>

          <ul className="flex flex-col gap-3.5">
            {ASSURANCES.map((assurance) => {
              const Icon = assurance.icon;
              return (
                <li
                  key={assurance.title}
                  className="flex items-start gap-3.5 rounded-[18px] border border-border/80 bg-white/75 px-5 py-5"
                >
                  <span className="inline-flex size-[38px] shrink-0 items-center justify-center rounded-xl bg-accent/70">
                    <Icon className="size-[19px] text-primary" />
                  </span>
                  <div className="flex flex-col gap-1">
                    <h3 className="text-base font-bold text-foreground">
                      {assurance.title}
                    </h3>
                    <p className="text-sm leading-snug text-foreground/70">
                      {assurance.body}
                    </p>
                  </div>
                </li>
              );
            })}
          </ul>
        </div>
      </Reveal>
    </section>
  );
}
