import {
  ChartLine,
  EyeOff,
  GraduationCap,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Reveal } from "@/components/landing/Reveal";
import { SHAPE } from "@/lib/design/shape";

interface Assurance {
  icon: LucideIcon;
  title: string;
  body: string;
}

const ASSURANCES: Assurance[] = [
  {
    icon: ShieldCheck,
    title: "Every Account Is Approved by Hand",
    body: "A new account waits for an administrator to approve it. Lessons start only after that.",
  },
  {
    icon: ChartLine,
    title: "Everything We Keep, Listed",
    body: "Email, name and goal; mastery and quiz answers; mistakes the lessons picked up; time and clicks per lesson; the pace that suits your child; and a log of AI requests.",
  },
  {
    icon: EyeOff,
    title: "The Microphone Waits for Your Child",
    body: "It turns on only when your child chooses to speak an answer, and speech to text is the browser's own. Aristo uses no camera or location, shows no ads, and sells nothing.",
  },
];

/**
 * Carries one of the page's three permitted eyebrows. It earns it: this is the
 * one point where the page stops talking to the student and starts talking to
 * the adult, and the reader needs to be told that.
 */
export function ForParents() {
  return (
    <section
      id="for-parents"
      className="relative z-10 mx-auto w-full max-w-6xl scroll-mt-16 px-5 pt-20 sm:px-8 lg:pt-28"
    >
      <Reveal>
        <div
          className={cn(
            SHAPE.band,
            "grid gap-10 border border-line bg-surface p-7 sm:p-10 lg:grid-cols-2 lg:gap-14 lg:p-14"
          )}
        >
          <div className="flex flex-col items-start gap-4">
            <span
              className={cn(
                SHAPE.pill,
                "inline-flex items-center gap-2 border border-tint-line bg-tint px-3.5 py-1.5 text-[11px] font-bold uppercase tracking-[0.14em] text-accent-text sm:text-xs"
              )}
            >
              <GraduationCap className="size-3.5" />
              For parents
            </span>
            <h2 className="text-balance text-[28px] font-extrabold leading-[1.08] tracking-[-0.02em] sm:text-4xl lg:text-[36px]">
              What Aristo Is, and What It Keeps
            </h2>
            <p className="text-base leading-relaxed text-body sm:text-[16.5px]">
              Aristo is an early prototype for grades 6 to 8. Its lessons are
              generated by AI and can be wrong. Learn alongside it, and check
              anything you would cite.
            </p>
          </div>

          <ul className="flex flex-col gap-3.5">
            {ASSURANCES.map((assurance) => {
              const Icon = assurance.icon;
              return (
                <li
                  key={assurance.title}
                  className={cn(
                    SHAPE.surface,
                    "flex items-start gap-3.5 border border-line bg-bg px-5 py-5"
                  )}
                >
                  <span
                    className={cn(
                      SHAPE.control,
                      "inline-flex size-[38px] shrink-0 items-center justify-center border border-line bg-surface"
                    )}
                  >
                    <Icon className="size-[19px] text-accent-text" />
                  </span>
                  <div className="flex flex-col gap-1">
                    <h3 className="text-base font-bold text-ink">
                      {assurance.title}
                    </h3>
                    <p className="text-sm leading-snug text-body">
                      {assurance.body}
                    </p>
                  </div>
                </li>
              );
            })}
          </ul>
        </div>
      </Reveal>
    </section>
  );
}
