import {
  ChartLine,
  EyeOff,
  GraduationCap,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Reveal } from "@/components/landing/Reveal";
import { SHAPE } from "@/components/landing/shape";

interface Assurance {
  icon: LucideIcon;
  title: string;
  body: string;
}

const ASSURANCES: Assurance[] = [
  {
    icon: ShieldCheck,
    title: "Nobody signs themselves in",
    body: "Every new account waits for an administrator to approve it before a single lesson can start.",
  },
  {
    icon: ChartLine,
    title: "We track learning, not behaviour",
    body: "Which concepts are mastered, what was answered, how long a lesson ran. That is the list.",
  },
  {
    icon: EyeOff,
    title: "No camera, no location, no ads",
    body: "The microphone is only ever used for an answer your child chooses to speak. Nothing here is sold on.",
  },
];

/**
 * Carries one of the page's three permitted eyebrows. It earns it: this is the
 * one point where the page stops talking to the student and starts talking to
 * the adult, and the reader needs to be told that.
 */
export function ForParents() {
  return (
    <section
      id="for-parents"
      className="relative z-10 mx-auto w-full max-w-6xl scroll-mt-16 px-5 pt-20 sm:px-8 lg:pt-28"
    >
      <Reveal>
        <div
          className={cn(
            SHAPE.band,
            "grid gap-10 border border-lp-line bg-lp-surface p-7 sm:p-10 lg:grid-cols-2 lg:gap-14 lg:p-14"
          )}
        >
          <div className="flex flex-col items-start gap-4">
            <span
              className={cn(
                SHAPE.pill,
                "inline-flex items-center gap-2 border border-lp-tint-line bg-lp-tint px-3.5 py-1.5 text-[11px] font-bold uppercase tracking-[0.14em] text-lp-accent-text sm:text-xs"
              )}
            >
              <GraduationCap className="size-3.5" />
              For parents
            </span>
            <h2 className="lp-display text-balance text-[26px] font-extrabold leading-[1.05] tracking-[-0.015em] sm:text-4xl lg:text-[32px]">
              For whoever is reading over their shoulder
            </h2>
            <p className="text-base leading-relaxed text-lp-body sm:text-[16.5px]">
              Aristo is an early prototype built for grades 6 to 8. Lessons are
              generated by AI, which means they can be wrong. It is something to
              learn alongside, not a source to cite.
            </p>
          </div>

          <ul className="flex flex-col gap-3.5">
            {ASSURANCES.map((assurance) => {
              const Icon = assurance.icon;
              return (
                <li
                  key={assurance.title}
                  className={cn(
                    SHAPE.surface,
                    "flex items-start gap-3.5 border border-lp-line bg-lp-bg px-5 py-5"
                  )}
                >
                  <span
                    className={cn(
                      SHAPE.control,
                      "inline-flex size-[38px] shrink-0 items-center justify-center border border-lp-line bg-lp-surface"
                    )}
                  >
                    <Icon className="size-[19px] text-lp-accent-text" />
                  </span>
                  <div className="flex flex-col gap-1">
                    <h3 className="text-base font-bold text-lp-ink">
                      {assurance.title}
                    </h3>
                    <p className="text-sm leading-snug text-lp-body">
                      {assurance.body}
                    </p>
                  </div>
                </li>
              );
            })}
          </ul>
        </div>
      </Reveal>
    </section>
  );
}
